<?php

use App\Models\DocRequerida;
use App\Models\TipoTraDocReq;
use Illuminate\Database\Seeder;

class DocRequeridaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	/*DocRequerida::truncate();
        $items = [
			[482,'Moratoria Dto.592/79','Se requiere el formulario de acogimiento a dicha Moratoria. Es de color azul, apaisado. Además, deberá remitir otro formulario que es de color gris, en caso de poseerlo.                                                                                      '],
			[483,'Moratoria ley 20147','Se requiere el formulario de acogimiento a dicha Moratoria. Es imprescindible además acompañar TODAS LAS BOLETAS PAGAS. En su defecto no podremos computar la moratoria mencionada.                                                                            '],
			[484,'Moratoria dto 2104/93','Se reuquiere: Fformulario de acogimiento a dicha Moratoria. Además deberá acompañar las boletas que haya pagado.                                                                                                                                               '],
			[485,'Documento de Identidad','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[486,'Solicitud de Prestaciones Previsionales','Con firma certificada por autoridad policial -SÓLO EN CAPITAL FEDERAL- (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[542,'Carta Poder','Con firma certificada por autoridad policial -SÓLO EN CAPITAL FEDERAL- (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[543,'Documento de identidad del Cónyuge/conviviente','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[544,'Partida de Matrimonio','partida de matrimonio actualizada (extendida por el registro civil donde se celebró el matrimonio, con no más de 6 meses de antigüedad); en caso de matrimonio celebrado en la Capital Federal, sólo adjuntar fotocopia simple de libreta de matrimonio.       '],
			[545,'Hijos menores de 18 años y/o discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[546,'Certificado de Domicilio','Extendido por la Policía y solo en caso de no tener el domicilio actualizado en el documento de identidad del titular del trámite.                                                                                                                             '],
			[557,'Documento de Identidad Cónyuge/Conviviente','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[559,'Hijos Menores de 18 años/Discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[562,'Formulario DGI 572 Y Carta de Devengamiento','Con firma simple del titular del trámite                                                                                                                                                                                                                       '],
			[564,'Poder AFIP','Se adjunta Formulario Nº3283, en el cual deberá certificar la firma donde se indica con una X, ante policía, Juzgado,  escribano, Centro de Gestión y Participación (este último sólo en Capital Federal).                                                     '],
			[565,'Formulario AFIP 460 o 560','Es el formulario de inscripción en Autónomos.                                                                                                                                                                                                                  '],
			[566,'Formulario AFIP 162','Es el formulario de Opción al  Monotributo (es el de color celeste que esta sellado por el Banco)                                                                                                                                                              '],
			[567,'Determinación de Obra Social','Con firma simple del titular del trámite.                                                                                                                                                                                                                      '],
			[568,'Boletas de pago Autónomos','Se requieren los originales de todas las boletas de pago de autónomos que obren en su poder.                                                                                                                                                                   '],
			[569,'Boletas de pago Monotributo','Se requieren todas las boletas de pago de Monotributo que obren en su poder.                                                                                                                                                                                   '],
			[570,'Certificación en AFJP','Convenir con personal del estudio encuentro en la AFJP. Deberá concurrir con ORIGINALES de DNI del titular y del conyuge/conviviente, de hijos menores/discapacitados, partidas de matrimonio/nacimiento, certificados escolaridad/discapacidad.               '],
			[571,'Formulario Baja Autónomos','Se requiere solo en caso de haberse dado de baja en Autónomos. Es el denominado con el Nº 929 o Nº569.                                                                                                                                                         '],
			[572,'Formulario Baja Monotributo','Se requiere solo en caso de haberse dado de baja en el Monotributo. Es el formulario Nº168F                                                                                                                                                                    '],
			[575,'Pantalla sellada AFIP','                                                                                                                                                                                                                                                               '],
			[578,'Partida de Defunción','                                                                                                                                                                                                                                                               '],
			[579,'Hijos Menores de 18 años o Discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[581,'Coincidencia Domiciliaria','En caso de no tener cónyuge y causante idéntico domicilio en DNI/Part. de defunción, deberá acompañarse pruebas que acrediten convivencia: pagos de servicios, cartas, etc.                                                                                    '],
			[582,'Formulario art. 1º','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[583,'Certificaciones de Servicios y Remuneraciones','Se requieren las certificaciones que posea, correspondiente a los empleadores para los cuales haya trabajado. Cada una debe estar firmada por el empleador correspondiente, con certificación de firma por Anses, Banco, Escribano o Juzgado. En caso que la misma esté extendida en hojas separadas, la firma y certificación debe constar en cada una de las hojas.'],
			[584,'Recibos de Sueldo','en los mismos deben constar lasretenciones en concepto de aportes jubilatorios, preferentemente con firma y aclaración de un representante del empleador                                                                                                       '],
			[585,'Conviviente: Declaración jurada (F.1.2.105)','Formulario de ANSES con firma del titular del trámite certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal).'],
			[586,'Constancia de Afiliación','Es la Constancia de Afiliación a las Ex Cajas de Previsión anterior a la asignación de Cuil. (Talon pequeño y alargado de papel grueso)                                                                                                                        '],
			[587,'Afectación de Haberes','Solo se requiere la que le expida el último empleador (esté o no cesado). Deber estar firmada por el mismo, con certificación de firma por Anses, Banco, escribano o Juzgado.'],
			[588,'Conviviente: pruebas documentales','Domicilios coincidentes en DNI; cuentas bancarias a nombre de ambos; extensión de tarjeta de crédito; a cargo en obra social; hijos en común; pasaportes; facturas de electrodomésticos/muebles; fotos;pago gastos de sepelio; etc.                            '],
			[589,'Opción al Régimen de Reparto','Es la constancia que acredita que Ud. ha optado por el Régimen de Reparto (Anses).                                                                                                                                                                             '],
			[590,'Telegrama Laboral','Se adjunta Telegrama Laboral Gratuito del Correo Argentino que deberá enviar. Luego remitir al estudio la constancia de envío.                                                                                                                                 '],
			[591,'Conviviente: Declaración Testimonial (F.1.2.106)','Formulario de ANSES de al menos 2 TESTIGOS con firma certificada por autoridad policial, judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal)o ANSES.                                               '],
			[592,'Ampliación de Certificación de Servicios','Desde la ultima fecha certificada con anterioridad y hasta el ultimo haber mensual percibido.'],
			[593,'Separados de Hecho: Declaración Jurada (F.1.2.107)','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal).'],
			[594,'Separados de Hecho: Declaración Testimonial (F.1.2.108)','Con al menos 2 TESTIGOS con firma certificada por autoridad policial, judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal)o ANSES.                                                                  '],
			[595,'Cese de Tareas Diferenciales','Es el formulario de Afectación de Haberes donde conste que ha cesado en las tareas de insalubres o diferenciales.'],
			[596,'Separados de Hecho: prueba documental','Toda documentación relativa a la separación: denuncia por abandono de hogar, sentencia de separación legal/divorcio, reserva de alimentos, recibos de sueldo con embargos por alimentos, etc.                                                                  '],
			[597,'Reconocimiento de Servicios Relación de Dependencia','Si posee en su poder algún expediente de reconocimiento de servicios (expedido por Anses, IPS, Policía, Caja Profesional) deberá presentarlo en el estudio en original y completo.                                                                             '],
			[603,'Hijos Menoras de 18 años o Discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[607,'Conviviente: Declaración Jurada F 2.1.105','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[608,'Conviviente: Prueba Documental','Domicilios coincidentes en DNI; cuentas bancarias a nombre de ambos; extensión de tarjeta de crédito; a cargo en obra social; hijos en común; pasaportes; facturas de electrodomésticos/muebles; fotos;pago gastos de sepelio; etc.                            '],
			[609,'Declaraciones Juradas Testimoniales Acreditacion de Servicios','Se acompañan dos formularios que deberán ser firmados por dos testigos (uno por formulario) ante una autoridad que le certifique la firma (Policía, Juzgado, escribano o Centro de Gestión y Participación (En Cap.Fed) .                                      '],
			[610,'Conviviente: Declaración Testimonial F 2.1.106','Formulario de ANSES de al menos 2 TESTIGOS con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL-, judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal)o ANSES.'],
			[611,'Conviviente: Información Sumaria','Con 2 testigos y notificación fehaciente a la AFJP del lugar y fecha de realización de la misma.                                                                                                                                                               '],
			[612,'Separados de Hecho: Declaración Jurada F 2.1. 107','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[613,'Separados de Hecho: Declaración Testimonial F 2.1.','Formulario de ANSES de al menos 2 TESTIGOS con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL-, judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal)o ANSES.'],
			[614,'Separados de Hecho: Pruebas Documentales','Toda documentación relativa a la separación: denuncia por abandono de hogar, sentencia de separación legal/divorcio, reserva de alimentos, recibos de sueldo con embargos por alimentos, etc.                                                                  '],
			[615,'Certificación de Servicios de Empleador en Quiebra','Sólo es válida la certificación que esté emitida o firmada por en Síndico con sello del Juzgado. Si no la posee, remitir nota informando el Juzgado en el cual se encuentra radicada la quiebra, nombre del Síndico actuante                                   '],
			[616,'Comprobante de afiliación a Obra Social o Gremio','                                                                                                                                                                                                                                                               '],
			[617,'Separados de Hecho: Información Sumaria','Con 2 testigos y notificación fehaciente a la AFJP del lugar y fecha de realización de la misma.                                                                                                                                                               '],
			[618,'Certificación en ANSES','Convenir con personal del estudio encuentro en la ANSES, sita en PARANA 451 PB. Deberá concurrir con ORIGINALES de DNI del titular y del conyuge/conviviente, de hijos menores/discapacitados, partidas de matrimonio/nacimiento, certificados escolaridad/discapacidad.'],
			[619,'Afectación de Haberes (casos especiales)','Deberá consignarse en el mismo los casos de renuncia por decreto.8820/62, 9202/62 y 557/63 o, si trabajando en una repartición Nacional su haber sufre descuentos de Seguro de Vida o Préstamo.                                                                '],
			[620,'Nota no más pruebas','Se remite nota donde consta que carece de otra documentación probatoria respecto al empleador. Deberá firmar la misma (firma simple)                                                                                                                           '],
			[621,'Reconocimiento de Servicios Autónomos','Si posee en su poder algún expediente de reconocimiento de servicios expedido por Anses, deberá presentarlo en el estudio en original y completo.                                                                                                              '],
			[622,'Personal Embarcado','Libreta de embarco y permiso de embarco o copia certificada.                                                                                                                                                                                                   '],
			[623,'Estibador Portuario','Libreta de afiliado (de poseerla); Documento Unico POrtuario (DUP) y Constancia expedida por la Prefectura Naval Argentina, en caso de no poseer DUP.                                                                                                          '],
			[624,'Aeronavegantes','Certificado extendido por la Fuerza Aérea, indicando horas de vuelo.                                                                                                                                                                                           '],
			[625,'Servicio Doméstico (Formularios)','Formularios que se adjuntan, con firma certificada por policía, escribano, Juzgado o Centro de Gestión y Participación. Una foto 4 x 4;                                                                                                                        '],
			[626,'Servicio Domestico (Prueba)','Libreta de Trabajo y Libreta sanitaria (de poseerlas); Toda constancia en la que figure su actividad como empleada en el servicio doméstico (declaración del padrón electoral, título de propiedad, créditos personales, carnet obra social/ mutual)           '],
			[631,'Servicio Doméstico (Prueba Continuación)','Certificados médicos extendidos por atención en el domicilio del empleador; Original de las boletas de depósito de aportes y contribuciones previsionales                                                                                                      '],
			[636,'Productores de Seguros','Certificaciones extendidas por servicios anteriores al 31/12/68, consignando los sueldos percibidos por todo el período en la moneda en que fueron abonados, como así también, fecha de primera y última operación.                                            '],
			[638,'Socio Gerente','Nota de Contador Público, avalada por el Consejo Profesional de Ciencias Económicas, donde consten alta y baja de las tareas administrativas y a qué cuenta se hallaba cargado el sueldo.                                                                      '],
			[642,'Prueba Documental','Libreta de maternidad; Libreta de trabajo a domicilio; Libreta de afiliación a Industria.                                                                                                                                                                      '],
			[643,'Separados de Hecho: Declaración Jurada F 2.1.107','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[644,'Construcción','Libreta de Fondo de Fondo Desempleo (de poseerla)                                                                                                                                                                                                              '],
			[646,'Fondo de Desempleo','Todos los recibos originales de cobro de desempleo que posea.                                                                                                                                                                                                  '],
			[648,'Informe Bancario','Formulario de ANSES certificado por el Banco donde el causante percibía su jubilación, con informe del último mes percibido.                                                                                                                                   '],
			[649,'Ultimo Recibo de Jubilación del Causante','                                                                                                                                                                                                                                                               '],
			[650,'Retiros Militares, de Prefectura o Gendarmería','Certificado extendido por la autoridad competente (militar)donde consten los períodos considerados para obtener el retiro militar. Detalle de los haberes percibidos en concepto de retiro desde la fecha de solicitud de beneficio a otorgar, hasta actualidad'],
			[651,'Retiro Policial','Constancia que indique si el retiro es por servicios civiles o policiales, servicios que fueron considerados para el otorgamiento del mismo (nacionales o provinciales). Detalle de haberes percibidos por el retiro, hasta la actualidad                      '],
			[652,'Certificado de Pluricobertura','Nota con membrete del empleador donde conste si el trabajador  percibe salario familiar y en caso de así ser, consigne datos de los familiares a cargo. La nota debe estar firmada por el empleador y certificada Banco, Anses, escribano o Juzgado.           '],
			[658,'Documento Identidad cónyuge/conviviente','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[660,'Hijos menores 18 años o discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[661,'Certificado Médico','Extendido con no más de 30 días; demás estudios; de poseer copia certificada de historia clínica                                                                                                                                                               '],
			[663,'Listado de médicos','Completar el formulario que se adjunta, con nombre, domicilio y teléfono de cada uno de los médicos que lo/a atendieron y atienden. Firmar al pie con firma simple.                                                                                            '],
			[664,'Declaración Jurada del Nivel de Educación alcanzad','Completar el formulario Nº PS.6.3 que se adjunta. Va con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal).-'],
			[666,'Documento Identidad del Titular','                                                                                                                                                                                                                                                               '],
			[671,'HIjos menores 18 o discapacitados','documento de identidad (fotocopia certificada dos primeras hojas y último domicilio), partida de nacimiento y certificado de escolaridad o discapacidad, según corresponda.                                                                                    '],
			[672,'Formulario DGI 572 y Carta Devengamiento','Firma simple del titular del trámite donde se indica con una X.                                                                                                                                                                                                '],
			[676,'Formulario 6.225','Retiro Transitorio por Invalidez. Cese en la Percepción de Remuneraciones. Si lo último que cobró fue desempleo, debe ser firmado por el titular del trámite (firma certificada por autoridad competente). De lo contrario firma último empleador.             '],
			[677,'Asignaciones Familiares','Formulario ANSES PS 2.14 con firma simple del titular del trámite.                                                                                                                                                                                             '],
			[696,'Carta Poder ANSES','Con firma certificada por autoridad policial -SOLO EN CAPITAL FEDERAL- (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[697,'Recibo de Haberes Previsionales','Recibo del año en curso original (que no corresponda a meses en que se percibe Aguinaldo)'],
			[698,'Resolución de Otorgamiento del Beneficio','Fotocopia Simple                                                                                                                                                                                                                                               '],
			[701,'Ultimo Recibo de Haberes Previsionales','Fotocopia Simple                                                                                                                                                                                                                                               '],
			[703,'Resolución de Otorgamiento/Denegatoria del Beneficio','Fotocopia Simple                                                                                                                                                                                                                                               '],
			[986,'Informacion Sumaria','Deberá concurrir al Juzgado correspondiente a su domicilio (o CGP para domiciliados en Capital Federal) con dos testigos a fin de exponer las circunstancias tendientes a acreditar la baja del aporte autónomo.'],
			[987,'Constancia de afiliacion negativa en Ingresos Brutos','Deberá concurrir a la municipalidad y solicitar constancia de no afiliación a Ingresos Brutos, o bien, si estuvo inscripto, la fecha de cancelación de dicha inscripción.'],
			[988,'Contrato Social','Fotocopia certificada del contrato de constitución de la sociedad'],
			[989,'Actas de Directorio','Copia certificada del acta donde conste su renuncia al cargo de director.'],
			[990,'Contrato de cesión de acciones','Copia certificada del contrato de venta o cesión de su participación en la sociedad.'],
			[1030,'Conprobantes de pago de servicios','De al menos dos servicios a nombre del titular coincidentes con el domicilio que figura en el documento.'],
			[1128,'Requerimiento de documentación (ANSES)','Se adjunta copia de la nota remitida por Anses a fin de que nos remita lo solicitado en la misma y en caso de no poseerlo nos informe a la brevedad. Plazo 15 días.'],
			[1130,'Requerimiento de documentación (AFJP)','Se adjunta copia de la nota remitida por AFJP a fin de que nos remita lo solicitado en la misma y en caso de no poseerlo nos informe a la brevedad. Plazo 15 días.'],
			[1137,'SOLICITUD','Firmada por el titular donde se indica con una (x) y certificada por escribano, Casa de la Pcia. de Bs.As. o Instituto de Previsión Social.'],
			[1138,'Ius previsional','$25 que deberá mandar al estudio a fin de que se abone en el Banco Provincia.'],
			[1139,'DNI titular','Fotocopia de las tres primeras hojas del DNI y del último domicilio, certificadas por escribano, Caja de la Pcia. de Bs.As. o Instituto de Previsión Social de la Pcia. de Bs.As.'],
			[1140,'DNI cónyuge','Fotocopia de las tres primeras hojas del DNI y del último domicilio, certificadas por escribano, Caja de la Pcia. de Bs.As. o Instituto de Previsión Social de la Pcia. de Bs.As.'],
			[1142,'Certificación Laboral','Fojas de servicio completa (certificación de servicios) expedida por el empleador, con firma certificada del mismo.'],
			[1158,'DNI','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación).'],
			[1159,'último recibo de pensión','original del último recibo de cobro de la jubilación del conviviente fallecido'],
			[1160,'carnet de jubilado/a','original del carnet de jubilado/a si lo tuviere'],
			[1165,'Información sumaria de convivencia (Pcia. de Bs. As.)','Deberá combinar con dos testigos (preferentemente vecinos) día y hora que concurrirán al Juzgado de Paz correspondiente a su domicilio.  Con una semana de anticipación enviar carta documento a la AFJP (conforme texto que se adjunta).  El día que concurran al Juzgado deberán hacerlo muñidos de DNI y personal del Juzgado les hará preguntas sobre la convivencia y les hará firmar el acta.   Luego remitir al estudio original del acta y de la carta documento enviado con su aviso de recepción.'],
			[1168,'Prueba de convivencia','En caso de no tener cónyuge y causante idéntico domicilio en DNI/Part. de defunción, deberá acompañarse pruebas que acrediten convivencia: pagos de servicios, cartas, etc.  Deberá remitir al estudio toda factura por servicios que este tanto a nombre del fallecido/a como del peticionante de la pensión, y toda otra prueba que acredite la coincidencia de domicilios.  Si tuvo hijos con el/la falecido/a, la documentación deberá remontarse a dos años antes del fallecimiento, hasta el acaecimiento del mismo.  Si no tuvo hijos con el/la causante deberá enviar prueba desde 5 años antes del fallecimiento.  En caso de haber percibido el seguro de vida, del fallecido/a, enviar constacia que así lo acredite.  Si ha estado afiliado a la obra social del fallecido/a enviar prueba de dicha afiliación.'],
			[1173,'Formulario Asignaciones Familiares','Se adjunta Formulario ANSES PS 2.14, que deberá firmar con firma simple del titular del trámite.'],
			[1209,'Cédula de Identidad','Original o copia certificada (por Escribano, Juzgado, Centro de Gestión y participación si se domicilia en Ciudad de Bs.As.)'],
			[1213,'Certificación de servicios y remuneraciones con certificacion contable','En caso de ser socio gerente de una SRL o Presidente de una SA y solo se aportó a autónomos pero no se efectuaron contribuciones en relación de dependencia, se deberá conseguir la certificación de servicios en donde conste en el rubro observaciones que se opta por lo dispuesto en el art.2 inc.2 de la ley 24241. A la misma se le debe adjuntar una certificación de contador público con la debida certificación de firma por parte del Consejo de Ciencias Económicas.'],
			[1228,'Escritura o contrato de locación','Escritura del inmueble o contrato de locación a nombre del titular (fotocopia certificada)'],
			[1255,'COMPROBACION FECHA INGRESO AL PAIS','PASAPORTE O CERTIFICADO DE MIGRACIONES (ORIGINALES O COPIAS CERTIFICADAS POR ESCRIBANO, JUEZ DE PAZ)'],
			[1298,'Clave Fiscal','Si ya tiene clave fiscal generada a traves de internet o en la agencia, deberá informarla al estudio.'],
			[1300,'Libreta de la construcción','Libreta de ingreso y egreso a cada empresa de la construcción, con la que se percibe el fondo de desempleo.'],
			[1332,'Transportista de carga','- Registro de conducir con categoría profesional (fotocopia certificada); Título de propiedad del automotor (copia certificada); Certificación provincial o municipal que habilita a transporte de cargas/fletes; Pólizas de seguro donde conste el destino del'],
			[1416,'Formulario PS 6.5.','Con sello de ANSES y firma del titular del beneficio,  debe ser completado por el Banco donde percibe los haberes.'],
			[1419,'Ultimo recibo de haberes','en caso de poseerlo'],
			[1420,'Fotocopia de la liquidación de ANSES','en caso de poseerla'],
			[1452,'TAXISTA PROPIETARIO','Licencia de conducir categ. profesional y sus renovaciones; certificado municipal de altas y bajas de patentes de vehiculos a su nombre; polizas de seguros; facturas compra de repuestos, boletera; verificación vehicular de SACTA.'],
			[1460,'Certificación del Sindicato','Solicitar en el sindicato correspondiente constancia donde conste número de afiliado, fecha de afiliación y de ser posible, periodos y empleadores por los que se recibió aportes a la entidad.'],
			[1652,'Documento Nacional de Identidad','Fotocopia simple de dos primeras hojas y ultimo domicilio (debe estar actualizado)'],
			[1653,'Solicitud de PAD','Con firma certificada por autoridad policial (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[1655,'Documentacion Laboral','En una segunda etapa se le requerira originales de documentacion laboral y personal.'],
			[1664,'Denuncia en AFIP','Deberá concurrir a la delegación de AFIP más cercana a su domicilio y presentar el formulario que se le entrega con fotocopia de la documentación adjunta al mismo. La AFIP le devuelve en el momento el duplicado del formulario y la documentación original, que deberá entregar en el estudio. Posteriormente recibira la RESOLUCION DE AFIP, que deberá traer al estudio.'],
			[1665,'Extranjeros','Si la fecha de ingreso al país no consta en su DNI, deberá acreditar la misma con alguna de la siguiente documentación: pasaporte, cedula de identidad, constancia de migraciones.'],
			[1735,'carta documento','Deberá ser enviada en el correo Argentino, y luego remitirnos la copia que le entregan.'],
			[1923,'SICAM (F 558 A/B/C)','En caso que Ud. ya haya detemrinado en alguna oportunidad la deuda a traves del sistema de AFIP'],
			[2172,'Resolucion acordatoria del beneficio','fotocopa simple'],
			[2174,'Documento de identidad del titular','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[2175,'Documento de identidad cónyuge','fotocopia certificada de dos primeras hojas y ultimo domicilio (autoridad certificante: Juzgados, Escribanos y en Capital Federal: Centros de Gestión y Participación) con la correspondiente legalización del Colegio de Escribanos cuando sea necesario (certificaciones en extraña jurisdicción)'],
			[2177,'Formulario ANSES P.S. 2.14','Con firma certificada por autoridad policial (con rango de oficial o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[2541,'Form.Certificación Negativa IPS','Con firma certificada por autoridad policial (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[2825,'DOCENTES: CEC 15 (Privados. Pcia. Bs. As.)','Para escuelas enseñanza privada en Pcia. de Buenso Aires; lo extiende el colegio y se certifica en DIPREGEP, calle 12 y 51, Torre 1, piso 10, La Plata'],
			[2826,'DOCENTES: Form. P.S. 6.268 (Cap. Fed. Privados)','Lo extiende el colegio, se certifica en Direccion General de Eduación de Gestión Privada, Santa Fé 4358, piso 1°, Capital Federal.  Autorizados a certificar: Areas, María Liliana o Boratto, Mercedes (Según Circular GP 61-05 ANSES)'],
			[2827,'DOCENTES:Form P.S. 6.268 (Cap. Fed. Ens. Pública)','Lo extiende el colegio, se certifica en Direccion Administrativa Docente, Avda. Paseo Colón 255, Capital Federal.  Autorizados a certificar: Medela Isabel o Ramírez Marcos (Según Circular GP 61-05 ANSES)  En caso de revistar en varios establecimientos, se solicita en el que tiene mayor carga horaria.'],
			[2828,'DOCENTES: Renuncia Condicionada dec. 8820','SOLO DOCENTES ENSEÑANZA PUBLICA  Se solicita en el establecimiento en que revista actualmente, juntamente con la certificacion de servicios y remuneraciones.'],
			[2829,'DOCENTES: P.S. 6.268 (Publicos- serv. anteriores a','Extiende el establecimiento, y se certifica en el Mrio. de Educación, Ciencia y Tecnología, Avda. Santa Fé 1548, piso 3 contrafrente, Capital Federal.'],
			[2830,'DOCENTES: Ens. Pública en la Pcia. de Buenos Aires','Reconocimiento de Servicios ante IPS, previa gestion del Codigo Jubilatorio en Direccion General de escuelas, direccion de jubilñaciones, calle 3 número 840, La Plata'],
			[2831,'DOCENTES: P.S. 6.268. (Pcia. Bs. As. Ens. Privada)','Lo extiende el colegio, se certifica en DIPREGEP, Calle 12 y 51, Torre 1, piso 10ireccion General de Eduación de Gestión Privada, Santa Fé 4358, piso 10 La Plata.  Autorizados a certificar: Mendy, Ramon Jorge (Según Circular GP 78-05 ANSES)'],
			[3799,'Form.ANSES - Pensión graciable','Con firma certificada por autoridad policial (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[3800,'Certificación AFJP de la CCI','Se deberá gestionar ante la AFJP nota informando saldo de la cuenta de capitalización individual (CCI)'],
			[3901,'Certificacion de Sueldo Actual','Certificación extendida por le empresa donde trabajaba, o en su defecto por la entidad sindical, donde conste el salario actual correspondiente a su categoria de retiro, incluida la antigüedad a ese momento.'],
			[3902,'Acta Poder Judicial','Concurrir al Juzgado de Paz o al Juzgado Federal correspondiente a su domicilio y firmar allí el formulario ACTA PODER que se adjunta al presente.'],
			[4128,'Minuta Acta Poder','Concurrir a Lavalle 1270 de 8 a 13 hs. con documento de identidad y formulario que le será proveído por el Estudio'],
			[4129,'Documentación Probatoria de Convivencia','Beneficiarios de seguros de vida; cuentas bancarias; partida de nacimiento de hijos en comun; contratos de alquiler; titulos de propiedad; constancias de obra social; etc.'],
			[4130,'Testigos','Nombre, dirección y ocupación de al menos 4 personar que puedan atestiguar acerca de la convivencia (no pueden ser familiares)'],
			[4131,'Relato de los hechos','Informar lugares de residencia anteriores; con quien se reside actualmente; estado civil del causante y peticionante; quien percibió el seguro de vida obligatorio.'],
			[4512,'Resumen de Cuenta de la AFJP','Ultimo resumen enviado por la AFJP  a la que se encontraba afiliado antes del regreso a reparto; es donde se informa cual es su saldo de la cuenta de capitalizacion individual.'],
			[4513,'Resolución de otorgamiento de beneficio','Copia simple de la resolución que le otorgó el beneficio de jubilación estatal (reparto)'],
			[4514,'Recibo de haberes jubilatorios','Copia simple del ultimo recibo de cobro de la jubilacion.'],
			[4515,'Certificación ante la AFJP','Convenir con personal del estudio para concurrir a la AFJP a fin de certificar firmas y comenzar con la gestión del retiro de los fondos capitalizados. Debe concurrir munido de su documento de identidad.'],
			[4528,'Resumen de la AFJP','Si en algún momento estuvo afiliado al regimen de capitalización (AFJP), adjuntar copia de el ultimo resumen de saldos enviado por la AFJP.'],
			[4558,'Form.253 - Aceptación de cuotas moratoria','Con firma certificada por autoridad policial (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[4812,'Formulario Certificación Negativa IPS','Con firma certificada por autoridad policial (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[4832,'Formulario de aceptación de descuento',''],
			[5477,'Formulario aceptación descuento','por el cual autoriza a la ANSES a realizar el descuento de las cuotas de moratoria pendientes de pago'],
			[5635,'Recibo de Pensión','Original de un recibo del beneficio de pensión.'],
			[5735,'Anexo 1 - Servicio Doméstico','Con firma certificada por autoridad policial -SÓLO EN CAPITAL FEDERAL- (con rango de subteniente o superior), judicial, escribano o funcionario del Centro de Gestión y Participación (este último solo para Capital Federal). Firmar en presencia del certificante donde se indica con X.'],
			[5780,'Partida de Matrimonio Original','Emitida con posterioridad al fallecimiento.  Si está emitida en la Capital Federal debe ser legalizada por la Cámara de Apelaciones, si está emitida por provincias del interior debe ser legalizada en el Ministerio del Interior, si está emitida por otros países debe ser legalizada en el Ministerio de Relaciones Exteriores -si están extendidas en otro idioma adjuntar traducción-'],
			[5781,'Partida de defunción Original','Si está emitida en la Capital Federal debe ser legalizada por la Cámara de Apelaciones, si está emitida por provincias del interior debe ser legalizada en el Ministerio del Interior, si está emitida por otros países debe ser legalizada en el Ministerio de Relaciones Exteriores -si están extendidas en otro idioma adjuntar traducción-'],
			[5782,'Último recibo de haberes Original','Del causante'],
			[5783,'Carnét de jubilado del causante',''],
			[5785,'Último resumen de cuenta, si cobraba por Banco Pro',''],
			[6047,'Designacion de apoderado para percibir','Carta poder ANSES firmada por poderdante y apoderado con firma certificada por autoridad policial (solo Capital Federal), autoridad judicial o escribano, fotocopia certificada documento de identidad del apoderado y en caso de ser familiar la partida que acredite el vinculo (Ej nacimiento, matrimonio)'],
						
        ];

        foreach ($items as $item) {
        	DocRequerida::create([
        		'id' => $item[0],
                'nombre' => trim($item[1]),
                'descripcion' => trim($item[2]),
        	]);
        }*/

        TipoTraDocReq::truncate();
        $items = [
			['Moratoria Dto.592/79',36],
			['Poder AFIP',36],
			['Formulario AFIP 460 o 560',36],
			['Moratoria ley 20147',36],
			['Moratoria dto 2104/93',36],
			['Formulario AFIP 162',36],
			['Boletas de pago Autónomos',36],
			['Boletas de pago Monotributo',36],
			['Formulario Baja Autónomos',36],
			['Formulario Baja Monotributo',36],
			['Pantalla sellada AFIP',36],
			['Reconocimiento de Servicios Autónomos',36],
			['Informacion Sumaria',36],
			['Constancia de afiliacion negativa en Ingresos Brutos',36],
			['Contrato Social',36],
			['Actas de Directorio',36],
			['Contrato de cesión de acciones',36],
			['Conprobantes de pago de servicios',36],
			['Certificado de domicilio',36],
			['Escritura o contrato de locación',36],
			['Clave Fiscal',36],
			['Transportista de carga',36],
			['TAXISTA PROPIETARIO',36],
			['SICAM (F 558 A/B/C)',36],
			['Certificaciones de Servicios y Remuneraciones',37],
			['Recibos de Sueldo',37],
			['Constancia de Afiliación',37],
			['Afectación de Haberes',37],
			['Opción al Régimen de Reparto',37],
			['Telegrama Laboral',37],
			['Ampliación de Certificación de Servicios',37],
			['Cese de Tareas Diferenciales',37],
			['Reconocimiento de Servicios Relación de Dependencia',37],
			['Declaraciones Juradas Testimoniales Acreditacion de Servicios',37],
			['Certificación de Servicios de Empleador en Quiebra',37],
			['Comprobante de afiliación a Obra Social o Gremio',37],
			['Afectación de Haberes (casos especiales)',37],
			['Nota no más pruebas',37],
			['Personal Embarcado',37],
			['Estibador Portuario',37],
			['Aeronavegantes',37],
			['Servicio Doméstico (Formularios)',37],
			['Documento de identidad',37],
			['Servicio Domestico (Prueba)',37],
			['Servicio Doméstico (Prueba Continuación)',37],
			['Productores de Seguros',37],
			['Socio Gerente',37],
			['Prueba Documental',37],
			['Construcción',37],
			['Fondo de Desempleo',37],
			['Retiros Militares, de Prefectura o Gendarmería',37],
			['Retiro Policial',37],
			['Certificado de Pluricobertura',37],
			['Certificación de servicios y remuneraciones con certificacion contable',37],
			['Libreta de la construcción',37],
			['Certificación del Sindicato',37],
			['Denuncia en AFIP',37],
			['carta documento',37],
			['DOCENTES: CEC 15 (Privados. Pcia. Bs. As.)',37],
			['DOCENTES: Form. P.S. 6.268 (Cap. Fed. Privados)',37],
			['DOCENTES:Form P.S. 6.268 (Cap. Fed. Ens. Pública)',37],
			['DOCENTES: Renuncia Condicionada dec. 8820',37],
			['DOCENTES: P.S. 6.268 (Publicos- serv. anteriores a',37],
			['DOCENTES: Ens. Pública en la Pcia. de Buenos Aires',37],
			['DOCENTES: P.S. 6.268. (Pcia. Bs. As. Ens. Privada)',37],
			['Documento de Identidad',42],
			['Solicitud de Prestaciones Previsionales',42],
			['Carta Poder',42],
			['Documento de identidad del Cónyuge/conviviente',42],
			['Partida de Matrimonio',42],
			['Hijos menores de 18 años y/o discapacitados',42],
			['Certificado de Domicilio',42],
			['Extranjeros',42],
			['Documento de identidad',43],
			['Solicitud de Prestaciones Previsionales',43],
			['Carta Poder',43],
			['Documento de Identidad del Cónyuge/Conviviente',43],
			['Partida de Matrimonio',43],
			['Hijos Menores de 18 Años y/o Discapacitados',43],
			['Certificado de Domicilio',43],
			['Certificación en ANSES',43],
			['Requerimiento de documentación',43],
			['Cédula de Identidad',43],
			['Fondo de Desempleo',43],
			['Extranjeros',43],
			['Form.Certificación Negativa IPS',43],
			['Form.ANSES - Pensión graciable',43],
			['Certificación AFJP de la CCI',43],
			['Resumen de la AFJP',43],
			['Formulario de aceptación de descuento',43],
			['Recibo de Pensión',43],
			['Anexo 1 - Servicio Doméstico',43],
			['Designacion de apoderado para percibir',43],
			['Clave Fiscal',43],
			['Formulario DGI 572 Y Carta de Devengamiento',44],
			['Documento de Identidad',44],
			['Solicitud de Prestaciones Previsionales',44],
			['Carta Poder',44],
			['Documento de Identidad Cónyuge/Conviviente',44],
			['Partida de Matrimonio',44],
			['Hijos Menores de 18 años/Discapacitados',44],
			['Formulario ANSES P.S. 2.14',44],
			['Certificado de Domicilio',44],
			['Determinación de Obra Social',44],
			['Certificación en AFJP',44],
			['Requerimiento de documentación',44],
			['Certificado de Pluricobertura',44],
			['Extranjeros',44],
			['Form.Certificación Negativa IPS',44],
			['Documento de identidad',45],
			['Solicitud de Prestaciones Previsionales',45],
			['Carta Poder',45],
			['Partida de Matrimonio',45],
			['Partida de Defunción',45],
			['Hijos Menores de 18 años o Discapacitados',45],
			['Certificado de Domicilio',45],
			['Coincidencia Domiciliaria',45],
			['Formulario art. 1º',45],
			['Conviviente: Declaración jurada (F.1.2.105)',45],
			['Conviviente: pruebas documentales',45],
			['Conviviente: Declaración Testimonial (F.1.2.106)',45],
			['Separados de Hecho: Declaración Jurada (F.1.2.107)',45],
			['Separados de Hecho: Declaración Testimonial (F.1.2.108)',45],
			['Separados de Hecho: prueba documental',45],
			['Certificación en ANSES',45],
			['COMPROBACION FECHA INGRESO AL PAIS',45],
			['Form.Certificación Negativa IPS',45],
			['Formulario aceptación descuento',45],
			['Anexo 1 - Servicio Doméstico',45],
			['Designacion de apoderado para percibir',45],
			['Documento de Identidad',46],
			['Solicitud de Prestaciones Previsionales',46],
			['Carta Poder',46],
			['Partida de Matrimonio',46],
			['Partida de Defunción',46],
			['Hijos Menoras de 18 años o Discapacitados',46],
			['Certificado de Domicilio',46],
			['Coincidencia Domiciliaria',46],
			['Formulario art. 1º',46],
			['Conviviente: Declaración Jurada F 2.1.105',46],
			['Conviviente: Declaración Jurada F 2.1.105',46],
			['Conviviente: Prueba Documental',46],
			['Conviviente: Declaración Testimonial F 2.1.106',46],
			['Conviviente: Información Sumaria',46],
			['Separados de Hecho: Declaración Jurada F 2.1. 107',46],
			['Separados de Hecho: Declaración Testimonial F 2.1.',46],
			['Separados de Hecho: Pruebas Documentales',46],
			['Separados de Hecho: Información Sumaria',46],
			['Asignaciones Familiares',46],
			['Formulario DGI 572 y Carta Devengamiento',46],
			['Determinación de Obra Social',46],
			['Requerimiento de documentación',46],
			['Form.Certificación Negativa IPS',46],
			['Documento de identidad',47],
			['Solicitud de Prestaciones Previsionales',47],
			['Carta Poder',47],
			['Partida de matrimonio',47],
			['Partida de Defunción',47],
			['Hijos Menores de 18 años o Discapacitados',47],
			['Certificado de Domicilio',47],
			['Coincidencia Domiciliaria',47],
			['Formulario Art. 1º',47],
			['Conviviente: Declaración testimonial F 2.1.106',47],
			['Conviviente: Prueba Documental',47],
			['Separados de Hecho: Declaración Jurada F 2.1.107',47],
			['Separados de Hecho: Declaración testimonial F 2.1.',47],
			['Separados de Hecho: Prueba Documental',47],
			['Informe Bancario',47],
			['Ultimo Recibo de Jubilación del Causante',47],
			['Form.253 - Aceptación de cuotas moratoria',47],
			['Formulario Certificación Negativa IPS',47],
			['Anexo 1 - Servicio Doméstico',47],
			['Designacion de apoderado para percibir',47],
			['Determinación de Obra Social',48],
			['DNI',48],
			['último recibo de pensión',48],
			['carnet de jubilado/a',48],
			['Información sumaria de convivencia (Pcia. de Bs. As.)',48],
			['Prueba de convivencia',48],
			['Partida de Defunción',48],
			['Solicitud de Prestaciones Previsionales',48],
			['Carta Poder',48],
			['Hijos menores de 18 años o discapacitados',48],
			['Formulario Asignaciones Familiares',48],
			['Formulario DGI 572 Y Carta de Devengamiento',48],
			['Conviviente: Declaración jurada (F.1.2.105)',48],
			['Conviviente: Declaración Testimonial (F.1.2.106)',48],
			['Certificación en AFJP',48],
			['Determinación de obra Social',48],
			['Requerimiento de documentacion',494],
			['Documento de Identidad',495],
			['Solicitud de Prestaciones Previsionales',495],
			['Carta Poder',495],
			['Documento Identidad cónyuge/conviviente',495],
			['Partida de Matrimonio',495],
			['Hijos menores 18 años o discapacitados',495],
			['Certificado Médico',495],
			['Listado de médicos',495],
			['Declaración Jurada del Nivel de Educación alcanzad',495],
			['Anexo 1 - Servicio Doméstico',495],
			['Formulario Certificación Negativa IPS',495],
			['Formulario de aceptación de descuento',495],
			['Documento Identidad del Titular',496],
			['Solicitud de Prestaciones Previsionales',496],
			['Carta Poder',496],
			['Documento Identidad Cónyuge/Conviviente',496],
			['Partida de Matrimonio',496],
			['HIjos menores 18 o discapacitados',496],
			['Formulario DGI 572 y Carta Devengamiento',496],
			['Formulario 6.225',496],
			['Asignaciones Familiares',496],
			['Certificación en AFJP',501],
			['Requerimiento de documentación',501],
			['Documento identidad del Titular',502],
			['Solicitud de Prestaciones Previsionales',502],
			['Carta Poder',502],
			['Documento de Identidad Cónyuge/Conviviente',502],
			['Partida de Matrimonio',502],
			['Hijos Menores de 18 años o Discapacitados',502],
			['Certificado de Domicilio',502],
			['Anexo 1 - Servicio Doméstico',502],
			['Requerimiento de documentación',503],
			['Form.Certificación Negativa IPS',503],
			['Documento de Identidad',504],
			['Solicitud de Prestaciones Previsionales',504],
			['Carta Poder',504],
			['Certificado de Domicilio',504],
			['Documento de Identidad',509],
			['Carta Poder ANSES',509],
			['Recibo de Haberes Previsionales',509],
			['Resolución de Otorgamiento del Beneficio',509],
			['Certificacion de Sueldo Actual',509],
			['Acta Poder Judicial',509],
			['Carta Poder',510],
			['Documento de Identidad',510],
			['Ultimo Recibo de Haberes Previsionales',510],
			['Resolución de Otorgamiento/Denegatoria del Beneficio',510],
			['Partida de matrimonio',511],
			['Resolucion acordatoria del beneficio',1025],
			['Ultimo recibo de haberes previsionales',1025],
			['Documento de identidad del titular',1025],
			['Documento de identidad cónyuge',1025],
			['Partida de Matrimonio',1025],
			['Carta Poder',1025],
			['Carta Poder',1134],
			['SOLICITUD',1134],
			['Ius previsional',1134],
			['DNI titular',1134],
			['DNI cónyuge',1134],
			['Certificación Laboral',1134],
			['Partida de Matrimonio Original',1134],
			['Partida de defunción Original',1134],
			['Último recibo de haberes Original',1134],
			['Carnét de jubilado del causante',1134],
			['Último resumen de cuenta, si cobraba por Banco Pro',1134],
			['Formulario PS 6.5.',1415],
			['Carta Poder',1415],
			['Documento de identidad',1415],
			['Ultimo recibo de haberes',1415],
			['Fotocopia de la liquidación de ANSES',1415],
			['Documento Nacional de Identidad',1651],
			['Solicitud de PAD',1651],
			['Carta Poder',1651],
			['Documentacion Laboral',1651],
			['Extranjeros',1651],
			['Minuta Acta Poder',4127],
			['Documentación Probatoria de Convivencia',4127],
			['Testigos',4127],
			['Relato de los hechos',4127],
			['Documento de Identidad',4510],
			['Resumen de Cuenta de la AFJP',4510],
			['Resolución de otorgamiento de beneficio',4510],
			['Recibo de haberes jubilatorios',4510],
			['Certificación ante la AFJP',4510],
        ];

        foreach ($items as $value) {
        	$id = DocRequerida::whereNombre($value[0])->first()->id;
        	TipoTraDocReq::create([
        		'tipo_tramite_id' => $value[1],
        		'doc_requerida_id' => $id,
        	]);
        }

    }
}
