<?php

use App\Models\Juzgado;
use Illuminate\Database\Seeder;

class JuzgadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	/*Juzgado::truncate();
        $items = [	
			[4579,'Seguridad Social N° 1                             ',1,1],
			[4621,'Seguridad Social N° 2                             ',1,1],
			[4622,'Seguridad Social N° 3                             ',1,1],
			[4623,'Seguridad Social N° 4                             ',1,1],
			[4624,'Seguridad Social N° 5                             ',1,1],
			[4625,'Seguridad Social N° 6                             ',1,1],
			[4626,'Seguridad Social N° 7                             ',1,1],
			[4627,'Seguridad Social N° 8                             ',1,1],
			[4628,'Seguridad Social N° 9                             ',1,1],
			[4629,'Seguridad Social N° 10                            ',1,1],
			[4630,'CFSS SALA I                                       ',1,1],
			[4631,'CFSS SALA II                                      ',1,1],
			[4632,'CFSS SALA III                                     ',1,1],
			[4633,'CORTE SUPREMA DE JUSTICIA DE LA NACION            ',1,1],

            [4634,'Juzgado laboral                                   ',1,2],
            [4635,'Juzgado civil                                     ',1,3],
            [4636,'Juzgado comercial                                 ',1,4],
            [4637,'Juzgado soc                                       ',1,5],

		];*/

        $items = [
/*['Juzgado Nacional en lo Civil Nº 1',3],
['Juzgado Nacional en lo Civil Nº 2',3],
['Juzgado Nacional en lo Civil Nº 3',3],
['Juzgado Nacional en lo Civil Nº 4',3],
['Juzgado Nacional en lo Civil Nº 5',3],
['Juzgado Nacional en lo Civil Nº 6',3],
['Juzgado Nacional en lo Civil Nº 7',3],
['Juzgado Nacional en lo Civil Nº 8',3],
['Juzgado Nacional en lo Civil Nº 9',3],
['Juzgado Nacional en lo Civil Nº 10',3],
['Juzgado Nacional en lo Civil Nº 11',3],
['Juzgado Nacional en lo Civil Nº 12',3],
['Juzgado Nacional en lo Civil Nº 13',3],
['Juzgado Nacional en lo Civil Nº 14',3],
['Juzgado Nacional en lo Civil Nº 15',3],
['Juzgado Nacional en lo Civil Nº 16',3],
['Juzgado Nacional en lo Civil Nº 17',3],
['Juzgado Nacional en lo Civil Nº 18',3],
['Juzgado Nacional en lo Civil Nº 19',3],
['Juzgado Nacional en lo Civil Nº 20',3],
['Juzgado Nacional en lo Civil Nº 21',3],
['Juzgado Nacional en lo Civil Nº 22',3],
['Juzgado Nacional en lo Civil Nº 23',3],
['Juzgado Nacional en lo Civil Nº 24',3],
['Juzgado Nacional en lo Civil Nº 25',3],
['Juzgado Nacional en lo Civil Nº 26',3],
['Juzgado Nacional en lo Civil Nº 27',3],
['Juzgado Nacional en lo Civil Nº 28',3],
['Juzgado Nacional en lo Civil Nº 29',3],
['Juzgado Nacional en lo Civil Nº 30',3],
['Juzgado Nacional en lo Civil Nº 31',3],
['Juzgado Nacional en lo Civil Nº 32',3],
['Juzgado Nacional en lo Civil Nº 33',3],
['Juzgado Nacional en lo Civil Nº 34',3],
['Juzgado Nacional en lo Civil Nº 35',3],
['Juzgado Nacional en lo Civil Nº 36',3],
['Juzgado Nacional en lo Civil Nº 37',3],
['Juzgado Nacional en lo Civil Nº 38',3],
['Juzgado Nacional en lo Civil Nº 39',3],
['Juzgado Nacional en lo Civil Nº 40',3],
['Juzgado Nacional en lo Civil Nº 41',3],
['Juzgado Nacional en lo Civil Nº 42',3],
['Juzgado Nacional en lo Civil Nº 43',3],
['Juzgado Nacional en lo Civil Nº 44',3],
['Juzgado Nacional en lo Civil Nº 45',3],
['Juzgado Nacional en lo Civil Nº 46',3],
['Juzgado Nacional en lo Civil Nº 47',3],
['Juzgado Nacional en lo Civil Nº 48',3],
['Juzgado Nacional en lo Civil Nº 49',3],
['Juzgado Nacional en lo Civil Nº 50',3],
['Juzgado Nacional en lo Civil Nº 51',3],
['Juzgado Nacional en lo Civil Nº 52',3],
['Juzgado Nacional en lo Civil Nº 53',3],
['Juzgado Nacional en lo Civil Nº 54',3],
['Juzgado Nacional en lo Civil Nº 55',3],
['Juzgado Nacional en lo Civil Nº 56',3],
['Juzgado Nacional en lo Civil Nº 57',3],
['Juzgado Nacional en lo Civil Nº 58',3],
['Juzgado Nacional en lo Civil Nº 59',3],
['Juzgado Nacional en lo Civil Nº 60',3],
['Juzgado Nacional en lo Civil Nº 61',3],
['Juzgado Nacional en lo Civil Nº 62',3],
['Juzgado Nacional en lo Civil Nº 63',3],
['Juzgado Nacional en lo Civil Nº 64',3],
['Juzgado Nacional en lo Civil Nº 65',3],
['Juzgado Nacional en lo Civil Nº 66',3],
['Juzgado Nacional en lo Civil Nº 67',3],
['Juzgado Nacional en lo Civil Nº 68',3],
['Juzgado Nacional en lo Civil Nº 69',3],
['Juzgado Nacional en lo Civil Nº 70',3],
['Juzgado Nacional en lo Civil Nº 71',3],
['Juzgado Nacional en lo Civil Nº 72',3],
['Juzgado Nacional en lo Civil Nº 73',3],
['Juzgado Nacional en lo Civil Nº 74',3],
['Juzgado Nacional en lo Civil Nº 75',3],
['Juzgado Nacional en lo Civil Nº 76',3],
['Juzgado Nacional en lo Civil Nº 77',3],
['Juzgado Nacional en lo Civil Nº 78',3],
['Juzgado Nacional en lo Civil Nº 79',3],
['Juzgado Nacional en lo Civil Nº 80',3],
['Juzgado Nacional en lo Civil Nº 81',3],
['Juzgado Nacional en lo Civil Nº 82',3],
['Juzgado Nacional en lo Civil Nº 83',3],
['Juzgado Nacional en lo Civil Nº 84',3],
['Juzgado Nacional en lo Civil Nº 85',3],
['Juzgado Nacional en lo Civil Nº 86',3],
['Juzgado Nacional en lo Civil Nº 87',3],
['Juzgado Nacional en lo Civil Nº 88',3],
['Juzgado Nacional en lo Civil Nº 89',3],
['Juzgado Nacional en lo Civil Nº 90',3],
['Juzgado Nacional en lo Civil Nº 91',3],
['Juzgado Nacional en lo Civil Nº 92',3],
['Juzgado Nacional en lo Civil Nº 93',3],
['Juzgado Nacional en lo Civil Nº 94',3],
['Juzgado Nacional en lo Civil Nº 95',3],
['Juzgado Nacional en lo Civil Nº 96',3],
['Juzgado Nacional en lo Civil Nº 97',3],
['Juzgado Nacional en lo Civil Nº 98:',3],
['Juzgado Nacional en lo Civil Nº 99',3],
['Juzgado Nacional en lo Civil Nº 100',3],
['Juzgado Nacional en lo Civil Nº 101',3],
['Juzgado Nacional en lo Civil Nº 102',3],
['Juzgado Nacional en lo Civil Nº 103',3],
['Juzgado Nacional en lo Civil Nº 104',3],
['Juzgado Nacional en lo Civil Nº 105',3],
['Juzgado Nacional en lo Civil Nº 106',3],
['Juzgado Nacional en lo Civil Nº 107',3],
['Juzgado Nacional en lo Civil Nº 108',3],
['Juzgado Nacional en lo Civil Nº 109',3],
['Juzgado Nacional en lo Civil Nº 110',3],
['Juzgado Nacional en lo Comercial Nº 1, Secretaría Nº 1',4],
['Juzgado Nacional en lo Comercial Nº 1, Secretaría Nº 2',4],
['Juzgado Nacional en lo  Comercial Nº 2, Secretaría Nº 3',4],
['Juzgado Nacional en lo Comercial Nº 2, Secretaría Nº 4',4],
['Juzgado Nacional en lo Comercial Nº 2, Secretaría Nº 200',4],
['Juzgado Nacional en lo Comercial Nº 3, Secretaría Nº 5',4],
['Juzgado Nacional en lo Comercial Nº 3, Secretaría Nº 6',4],
['Juzgado Nacional en lo Comercial Nº 4, Secretaría Nº 7',4],
['Juzgado Nacional en lo Comercial Nº 4, Secretaría Nº 8',4],
['Juzgado Nacional en lo Comercial Nº 5, Secretaría Nº 9',4],
['Juzgado Nacional en lo Comercial Nº 5, Secretaría Nº 10',4],
['Juzgado Nacional en lo Comercial Nº 6, Secretaría Nº 11',4],
['Juzgado Nacional en lo Comercial Nº 6, Secretaría Nº 12',4],
['Juzgado Nacional en lo Comercial Nº 7, Secretaría Nº 13',4],
['Juzgado Nacional en lo Comercial Nº 7, Secretaría Nº 14',4],
['Juzgado Nacional en lo Comercial Nº 8, Secretaría Nº 15',4],
['Juzgado Nacional en lo Comercial Nº 8, Secretaría Nº 16',4],
['Juzgado Nacional en lo Comercial Nº 9, Secretaría Nº 17',4],
['Juzgado Nacional en lo Comercial Nº 9, Secretaría Nº 18',4],
['Juzgado Nacional en lo Comercial Nº 10, Secretaría Nº 19',4],
['Juzgado Nacional en lo Comercial Nº 10, Secretaría Nº 20',4],
['Juzgado Nacional en lo Comercial Nº 10, Secretaría Nº 100',4],
['Juzgado Nacional en lo Comercial Nº 11, Secretaría Nº 21',4],
['Juzgado Nacional en lo Comercial Nº 11, Secretaría Nº 22',4],
['Juzgado Nacional en lo Comercial Nº 12, Secretaría Nº 23',4],
['Juzgado Nacional en lo Comercial Nº 12, Secretaría Nº 24',4],
['Juzgado Nacional en lo Comercial Nº 12, Secretaría Nº 120',4],
['Juzgado Nacional en lo Comercial Nº 13, Secretaría Nº 25',4],
['Juzgado Nacional en lo Comercial Nº 13, Secretaría Nº 26',4],
['Juzgado Nacional en lo Comercial Nº 14, Secretaría Nº 27',4],
['Juzgado Nacional en lo Comercial Nº 14, Secretaría Nº 28',4],
['Juzgado Nacional en lo Comercial Nº 15, Secretaría Nº 29',4],
['Juzgado Nacional en lo Comercial Nº 15, Secretaría Nº 30',4],
['Juzgado Nacional en lo Comercial Nº 16, Secretaría Nº 31',4],
['Juzgado Nacional en lo Comercial Nº 16, Secretaría Nº 32',4],
['Juzgado Nacional en lo Comercial Nº 16, Secretaría Nº 160',4],
['Juzgado Nacional en lo Comercial Nº 17, Secretaría Nº 33',4],
['Juzgado Nacional en lo Comercial Nº 17, Secretaría Nº 34',4],
['Juzgado Nacional en lo Comercial Nº 18, Secretaría Nº 35',4],
['Juzgado Nacional en lo Comercial Nº 18, Secretaría Nº 36',4],
['Juzgado Nacional en lo Comercial Nº 19, Secretaría Nº 37',4],
['Juzgado Nacional en lo Comercial Nº 19, Secretaría Nº 38',4],
['Juzgado Nacional en lo Comercial Nº 20, Secretaría Nº 39',4],
['Juzgado Nacional en lo Comercial Nº 20, Secretaría Nº 40',4],
['Juzgado Nacional en lo Comercial Nº 21, Secretaría Nº 41',4],
['Juzgado Nacional en lo Comercial Nº 21, Secretaría Nº 42',4],
['Juzgado Nacional en lo Comercial Nº 22, Secretaría Nº 43',4],
['Juzgado Nacional en lo Comercial Nº 22, Secretaría Nº 44',4],
['Juzgado Nacional en lo Comercial Nº 23, Secretaría Nº 45',4],
['Juzgado Nacional en lo Comercial Nº 23, Secretaría Nº 46',4],
['Juzgado Nacional en lo Comercial Nº 23, Secretaría Nº 230',4],
['Juzgado Nacional en lo Comercial Nº 24, Secretaría Nº 47',4],
['Juzgado Nacional en lo Comercial Nº 24, Secretaría Nº 48',4],
['Juzgado Nacional en lo Comercial Nº 24, Secretaría Nº 240',4],
['Juzgado Nacional en lo Comercial Nº 25, Secretaría Nº 49',4],
['Juzgado Nacional en lo Comercial Nº 25, Secretaría Nº 50',4],
['Juzgado Nacional en lo Comercial Nº 26, Secretaría Nº 51',4],
['Juzgado Nacional en lo Comercial Nº 26, Secretaría Nº 52',4],
['Juzgado Nacional en lo Comercial Nº 27, Secretaría Nº 53',4],
['Juzgado Nacional en lo Comercial Nº 27, Secretaría Nº 54',4],
['Juzgado Nacional en lo Comercial Nº 28, Secretaría Nº 55',4],
['Juzgado Nacional en lo Comercial Nº 28, Secretaría Nº 56',4],
['Juzgado Nacional en lo Comercial Nº 29, Secretaría Nº 57',4],
['Juzgado Nacional en lo Comercial Nº 29, Secretaría Nº 58',4],
['Juzgado Nacional en lo Comercial Nº 30, Secretaría Nº 59',4],
['Juzgado Nacional en lo Comercial Nº 30, Secretaría Nº 60',4],
['Juzgado Nacional en lo Comercial Nº 31, Secretaría Nº 61',4],
['Juzgado Nacional en lo Comercial Nº 31, Secretaría Nº 62',4],*/
['Juzgado 1 - Diagonal Roque Sáenz Peña 760 1º'],
['Juzgado 2 - Diagonal Roque Sáenz Peña 760 1º'],
['Juzgado 3 - Diagonal Roque Sáenz Peña 760 6º'],
['Juzgado 4 - Diagonal Roque Sáenz Peña 760 7º'],
['Juzgado 5 - Diagonal Roque Sáenz Peña 760 7º'],
['Juzgado 6 - Diagonal Roque Sáenz Peña 760 7º'],
['Juzgado 7 - Diagonal Roque Sáenz Peña 760 2º'],
['Juzgado 8 - Diagonal Roque Sáenz Peña 760 1º'],
['Juzgado 9 - Diagonal Roque Sáenz Peña 760 8º'],
['Juzgado 10 - Diagonal Roque Sáenz Peña 760 8º'],
['Juzgado 11 - Diagonal Roque Sáenz Peña 760 6º'],
['Juzgado 12 - Diagonal Roque Sáenz Peña 760 6º'],
['Juzgado 13 - Diagonal Roque Sáenz Peña 760 8º'],
['Juzgado 14 - Teniente Gral. J.D. Perón 990 1º'],
['Juzgado 15 - Diagonal Roque Sáenz Peña 760 9º'],
['Juzgado 16 - Diagonal Roque Sáenz Peña 760 9º'],
['Juzgado 17 - Diagonal Roque Sáenz Peña 760 9º'],
['Juzgado 18 - Sarmiento 1118 7º'],
['Juzgado 19 - Diagonal Roque Sáenz Peña 760 10º'],
['Juzgado 20 - Diagonal Roque Sáenz Peña 760 2º'],
['Juzgado 21 - Diagonal Roque Sáenz Peña 760 2º'],
['Juzgado 22 - Lavalle 1268 3º'],
['Juzgado 23 - Lavalle 1268 1º'],
['Juzgado 24 - Diagonal Roque Sáenz Peña 760 3º'],
['Juzgado 25 - Diagonal Roque Sáenz Peña 760 3º'],
['Juzgado 26 - Teniente Gral. J.D. Perón 990 2º'],
['Juzgado 27 - Teniente Gral. J.D. Perón 990 3º'],
['Juzgado 28 - Diagonal Roque Sáenz Peña 760 3º'],
['Juzgado 29 - Diagonal Roque Sáenz Peña 760 4º'],
['Juzgado 30 - Teniente Gral. J.D. Perón 990 4º'],
['Juzgado 31 - Teniente Gral. J.D. Perón 990 5º'],
['Juzgado 32 - Diagonal Roque Sáenz Peña 760 4º'],
['Juzgado 33 - Diagonal Roque Sáenz Peña 760 4º'],
['Juzgado 34 - Teniente Gral. J.D. Perón 990 6º'],
['Juzgado 35 - Teniente Gral. J.D. Perón 990 7º'],
['Juzgado 36 - Diagonal Roque Sáenz Peña 760 5º'],
['Juzgado 37 - Diagonal Roque Sáenz Peña 760 5º'],
['Juzgado 38 - Teniente Gral. J.D. Perón 990 8º'],
['Juzgado 39 - Teniente Gral. J.D. Perón 990 3º'],
['Juzgado 40 - Diagonal Roque Sáenz Peña 760 5º'],
['Juzgado 41 - Cerrito 264 6º'],
['Juzgado 42 - Cerrito 264 6º'],
['Juzgado 43 - Sarmiento 1118 7º'],
['Juzgado 44 - Sarmiento 1118 8º'],
['Juzgado 45 - Cerrito 264 7º'],
['Juzgado 46 - Lavalle 1268 5º'],
['Juzgado 47 - Lavalle 1268 5º'],
['Juzgado 48 - Lavalle 1268 5º'],
['Juzgado 49 - Lavalle 1268 4º'],
['Juzgado 50 - Lavalle 1268 4º'],
['Juzgado 51 -  Lavalle 1268 4º'],
['Juzgado 52 - Lavalle 1268 1º'],
['Juzgado 53 - Lavalle 1268 1º'],
['Juzgado 54 - Lavalle 1268 1º'],
['Juzgado 55 - Lavalle 1268 1º'],
['Juzgado 56 - Lavalle 1268 2º'],
['Juzgado 57 - Lavalle 1268 2º'],
['Juzgado 58 - Lavalle 1268 2º'],
['Juzgado 59 - Lavalle 1268 2º'],
['Juzgado 60 - Lavalle 1268 PB'],
['Juzgado 61 - Lavalle 1268 PB'],
['Juzgado 62 - Lavalle 1268 PB'],
['Juzgado 63 - Lavalle 1268 PB'],
['Juzgado 64 - Lavalle 1268 PB'],
['Juzgado 65 - Lavalle 1268 3º'],
['Juzgado 66 - Lavalle 1268 3º'],
['Juzgado 67 - Lavalle 1268 3º'],
['Juzgado 68 - Paraná 520 9º'],
['Juzgado 69 - Teniente Gral. J.D. Perón 990 10º'],
['Juzgado 70 - Paraná 520 2º'],
['Juzgado 71 - Paraná 520 9º'],
['Juzgado 72 - Teniente Gral. J.D. Perón 990 2º'],
['Juzgado 73 - Teniente Gral. J.D. Perón 990 11º'],
['Juzgado 74 - Teniente Gral. J.D. Perón 990 3º'],
['Juzgado 75 - Paraná 520 10º'],
['Juzgado 76 - Teniente Gral. J.D. Perón 990 4º'],
['Juzgado 77 - Teniente Gral. J.D. Perón 990 12º'],
['Juzgado 78 - Teniente Gral. J.D. Perón 990 5º'],
['Juzgado 79 - Paraná 520 11º'],
['Juzgado 80 - Paraná 520 10º C.P.'],
['San Isidro 1 - Ituzaingo 340'],
['San Isidro 2 - Ituzaingo 340'],
['San Isidro 3 - Ituzaingo 340'],
['San Isidro 4 - Terrero 54'],
['San Isidro 5 - Terrero 64'],
['San Isidro 6 - Maipú 1-19'],
['San Isidro 7 - Nazarre 1030 (PILAR)'],
['Moreno -  Merlo 2719']
        ];

        foreach ($items as $item) {
        	Juzgado::create([
        		'nombre' => trim($item[0]),
        		'vigente' => true,
                'area_id' => 2
        	]);
        }
    }
}
